
import static java.lang.Character.isDigit;
import static java.lang.Character.isLetter;
import static java.lang.Character.isWhitespace;
import java.util.Stack;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author farid
 */
public class NewJFrame extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame
	 */
	public NewJFrame() {
		initComponents();
		 
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        dtype = new javax.swing.JDialog();
        lval = new java.awt.List();
        jButton8 = new javax.swing.JButton();
        ltype = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dtbl = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        lfirst = new java.awt.List();
        lfollow = new java.awt.List();
        vt8 = new java.awt.List();
        t6 = new java.awt.List();
        vt1 = new java.awt.List();
        vt2 = new java.awt.List();
        t9 = new java.awt.List();
        jLabel8 = new javax.swing.JLabel();
        vt3 = new java.awt.List();
        jLabel9 = new javax.swing.JLabel();
        vt4 = new java.awt.List();
        jLabel10 = new javax.swing.JLabel();
        vt6 = new java.awt.List();
        vt5 = new java.awt.List();
        vt7 = new java.awt.List();
        lvn = new java.awt.List();
        vt0 = new java.awt.List();
        t1 = new java.awt.List();
        t2 = new java.awt.List();
        t3 = new java.awt.List();
        t4 = new java.awt.List();
        t7 = new java.awt.List();
        t8 = new java.awt.List();
        t5 = new java.awt.List();
        jButton9 = new javax.swing.JButton();
        accpt = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        act = new java.awt.List();
        lpile = new java.awt.List();
        lpile1 = new java.awt.List();
        jLabel5 = new javax.swing.JLabel();

        jDialog1.setTitle("Error !!");
        jDialog1.setAlwaysOnTop(true);
        jDialog1.setBackground(new java.awt.Color(255, 255, 255));
        jDialog1.setBounds(new java.awt.Rectangle(100, 100, 400, 130));
        jDialog1.setFont(new java.awt.Font("Adobe Naskh Medium", 0, 12)); // NOI18N
        jDialog1.setResizable(false);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton7.setText("close");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(0, 438, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addComponent(jTextField1))
                .addGap(21, 21, 21))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        dtype.setTitle("Type");
        dtype.setBounds(new java.awt.Rectangle(300, 100, 300, 400));
        dtype.setResizable(false);

        jButton8.setText("Close");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Valeur");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Type");

        javax.swing.GroupLayout dtypeLayout = new javax.swing.GroupLayout(dtype.getContentPane());
        dtype.getContentPane().setLayout(dtypeLayout);
        dtypeLayout.setHorizontalGroup(
            dtypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtypeLayout.createSequentialGroup()
                .addGroup(dtypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dtypeLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton8))
                    .addGroup(dtypeLayout.createSequentialGroup()
                        .addGroup(dtypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dtypeLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lval, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dtypeLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(dtypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ltype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dtypeLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)))))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        dtypeLayout.setVerticalGroup(
            dtypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dtypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dtypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ltype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lval, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jButton8)
                .addContainerGap())
        );

        dtbl.setTitle("Table analyse, Follow, First");
        dtbl.setBounds(new java.awt.Rectangle(200, 100, 880, 535));
        dtbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dtbl.setResizable(false);

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("First");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Follow");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Table analyse");

        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });

        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });

        jButton9.setText("Close");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lfollow, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lvn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(vt0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(vt1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vt3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vt4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vt6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vt7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton9)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lfollow, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vt1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt0, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vt8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lvn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        javax.swing.GroupLayout dtblLayout = new javax.swing.GroupLayout(dtbl.getContentPane());
        dtbl.getContentPane().setLayout(dtblLayout);
        dtblLayout.setHorizontalGroup(
            dtblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtblLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dtblLayout.setVerticalGroup(
            dtblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtblLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        accpt.setTitle("Accepted");
        accpt.setBackground(new java.awt.Color(255, 255, 255));
        accpt.setBounds(new java.awt.Rectangle(400, 200, 300, 200));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton10.setText("Close");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SharedScreenshot.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Accepted .");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout accptLayout = new javax.swing.GroupLayout(accpt.getContentPane());
        accpt.getContentPane().setLayout(accptLayout);
        accptLayout.setHorizontalGroup(
            accptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accptLayout.setVerticalGroup(
            accptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilteur");
        setBounds(new java.awt.Rectangle(100, 100, 520, 305));
        setResizable(false);

        jButton1.setText("Show file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Run");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Quit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Adobe Naskh Medium", 1, 11)); // NOI18N
        jLabel2.setText("Action");

        jLabel1.setFont(new java.awt.Font("Adobe Naskh Medium", 1, 11)); // NOI18N
        jLabel1.setText("Pile");

        jButton2.setText("show grammar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("show types table");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("show analyzes table");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        act.setBackground(new java.awt.Color(102, 102, 102));
        act.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        act.setForeground(new java.awt.Color(102, 255, 0));
        act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actActionPerformed(evt);
            }
        });

        lpile.setBackground(new java.awt.Color(102, 102, 102));
        lpile.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lpile.setForeground(new java.awt.Color(102, 255, 0));
        lpile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpileActionPerformed(evt);
            }
        });

        lpile1.setBackground(new java.awt.Color(102, 102, 102));
        lpile1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lpile1.setForeground(new java.awt.Color(102, 255, 0));

        jLabel5.setFont(new java.awt.Font("Adobe Naskh Medium", 1, 11)); // NOI18N
        jLabel5.setText("Expression");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addComponent(lpile1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(78, 78, 78)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lpile, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(act, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(40, 40, 40)
                        .addComponent(jButton4)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(lpile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lpile1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(act, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //show file
            // TODO add your handling code here:
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + "C:\\Users\\Afak\\Desktop\\framecompl\\text.txt");
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Check file details");
        }

    }//GEN-LAST:event_jButton1ActionPerformed
     int nbtyp;
	 typ tbltyp[] ;
	 readR red = new readR();
	 String First[];
	 String [] Follow;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //run
        // TODO add your handling code here:
		editfile file = new editfile();
		// file.editf();
		file.readf();
		
    int n = file.data.length();   
    String c = ""; 
    tbltyp = new typ[n];
    int i = 0;
    int j = 0;
    while (i < n ) {
        if ((i < n ) && isLetter(file.data.charAt(i))) {
            boolean b1 = isLetter(file.data.charAt(i));
            boolean b2 = isDigit(file.data.charAt(i));
            while ( (i < n) && (b1 || b2)) {
                c = c + file.data.charAt(i);
                i++;
                if(i<n){
                     b1 = isLetter(file.data.charAt(i));
                     b2 = isDigit(file.data.charAt(i)); 
                }
                
            }
           tbltyp[j] = new typ(c , "Identifier") ;
           j++;
           c = "";
        } 
        else {
        if ((i < n ) && isDigit(file.data.charAt(i))) {
            while ( (i < n ) && isDigit(file.data.charAt(i)) ){
                c = c + file.data.charAt(i);
                i++;  
            }
            tbltyp[j] = new typ(c , "Integer") ;
            j++;
            c = "";
        }
        else {
        if ( (i < n ) && (  (file.data.charAt(i) == '+') ||(file.data.charAt(i) == '-')  || (file.data.charAt(i) == '*')  || (file.data.charAt(i) == '/') ) ){
            c = c + file.data.charAt(i);
            tbltyp[j] = new typ(c , c );
            j++;
            c = "";
            i++;
            
        } 
        else {
        if ( (i < n ) && (file.data.charAt(i) == '(' || file.data.charAt(i) == ')' ) ){
            c = c + file.data.charAt(i);
            tbltyp[j] = new typ(c , c );
            j++;
            c = "";
            i++;
        }
        else {
        if ( (i < n ) && isWhitespace(file.data.charAt(i))) {
            i++;
        }
        else {
            c = c + file.data.charAt(i);
            tbltyp[j] = new typ(c , "unknown" );
            j++;
            c = "";
            i++;
            
        }
        }
        }
        }
        }
    }
    
    nbtyp = j;
    boolean unknown = false ;
	String unk="";
    for (i=0;i<nbtyp;i++){
        if ("unknown".equals(tbltyp[i].ty)){
            unknown = true;
			unk = unk + tbltyp[i].val + " ";
        }
    }
    
    if(unknown){
		jDialog1.setVisible(true);
		jTextField1.setText("i do not know what is this caractere : " + unk);
    }
    else{
// part 2
        
        red.calcu();
		red.CreateT(red.nb, red.tb);
        red.tblx();
      //  red.affichex();
        red.Remplir();
//        red.affichtab();
        red.RempVn();
//first
        j=0;
        n=red.nb;
        First= new String[n];
        i=0;
        while(i<n)
        {
            boolean b= true;
           First[i]="";
           First[i]=red.First(i, red.Tab, b,true,i," ");
           i++;
         }
 // follow
        int nn,ii;
        nn=red.nb;
		Follow = new String [nn];
        ii=0;
     while(ii < nn ){
         String ss;
         ss = red.Tab[ii][0];
         Follow[ii] = red.Follow(ss, red.Tab) ;
         ii++;
     }
// dok nrigl tabl ta3 folow mn li mdobliyin	 
     String sf,ssf,cc;
	 ii=0;
	 while (ii<nn){
		 sf = Follow[ii];
		 ssf = "";
		 int i0=0,in;
		 in = sf.length();
		 while (i0<in){
			 cc="";
			 boolean bs=true;
			 while (bs && i0<in){
				 if (isWhitespace(sf.charAt(i0))) {
				 bs = false;
				 }
				else 
				{
				 cc = cc + sf.charAt(i0); 
				 }
				 i0++;
			 }
			 if ( ( cc != "" ) && ( !ssf.contains(cc) )){
				 ssf = ssf + " "+ cc;
			 }
			 
		 }
		 
	 Follow[ii] = ssf ;
	 ii++;

	 }
	 
// ykamal y3amar table analyse bl follow
	 i=0;
     while(i<n){
		 if (First[i].contains("EPSILO")){
			  
			 String flw,t="";
			 flw = Follow[i]+ " ";
			 int i0=0,in=flw.length();
			 for (i0=0;i0<in;i0++){
				 if( flw.charAt(i0)==' '){
					 if(t!=""){
						 int i3=0;
						 boolean bb1 = true;
						 while(bb1){
							 if (red.Vt[i3].equals(t)){
								 bb1 = false;
							 }
							 else{
								 i3++;
							 }
						 }
						 red.Table[i][i3]= "EPSILO";
						 t="";
					 }
					 
				 }
				 else {
					 t = t + flw.charAt(i0);
				 }
			 }
		 }
			 i++;
	 }
	 
//hna tabda 7kayat pile
		act.removeAll();
		lpile.removeAll();
		lpile1.removeAll();
		Stack p1 = new Stack();
		Stack p2 = new Stack();
		p1.push("#");
		p2.push("#");
		
		for(i=nbtyp-1;i>=0;i--){
			p1.push(tbltyp[i].ty);
		}
		boolean b=false;
		i=0;
		while(!b) {
			if (p1.peek().equals(red.Vt[i])){
				b=true;
			}
			else{
				i++;
			}
		}
		String ss= red.Table[0][i];
		StringTokenizer st = new StringTokenizer(ss," ");
		int n1=st.countTokens();
		Stack p3 = new Stack();
		for(i=0;i<n1;i++)
		{
			p3.push(st.nextToken());
		}
		while(!p3.empty()){
			p2.push(p3.peek());
			p3.pop();
		}
		lpile.add(p2.toString());
		lpile1.add(p1.toString());
		boolean accept=true;
		while((!p2.empty()) &&(accept)){
			if(p1.peek().equals(p2.peek())){
				act.add("Matching");
				p1.pop();
				p2.pop();
				lpile.add(p2.toString());
				lpile1.add(p1.toString());
			}
			else{
				if( ((p1.peek().equals("#")) && (!p2.peek().equals("#")) )|| ((!p1.peek().equals("#")) && (p2.peek().equals("#"))) ){
					if((!p1.peek().equals("#")) && (p2.peek().equals("#")))
					{
						accept = false;
					}
					else{

						b=false;
						i=0;
						while(!b) {
						  if (p1.peek().equals(red.Vt[i])){
						  b=true;
						  }
						   else{
							   i++;
							}
						}
						j=0;
						b=false;
						while(!b) {
						  if (p2.peek().equals(red.Vn[j])){
						  b=true;
						  }
						   else{
							   j++;
							}
						}
						ss=red.Table[j][i];
						System.out.println(p1.peek() + " === " + p2.peek() + " +++ " + ss );
						if(ss.equals("EPSILO")){
							p2.pop();
							lpile.add(p2.toString());
							lpile1.add(p1.toString());
							act.add("Matching E");
							}
							else{

							accept = false;
							}
				
					}
				}
				else{
				b=false;
		        i=0;
		        while(!b) {
			      if (p1.peek().equals(red.Vt[i])){
				  b=true;
			      }
			       else{
				       i++;
			        }
		        }
				j=0;
				b=false;
				while(!b) {
			      if (p2.peek().equals(red.Vn[j])){
				  b=true;
			      }
			       else{
				       j++;
			        }
		        }
				ss=red.Table[j][i];
				if(ss.equals("EPSILO")){
					p2.pop();
					lpile.add(p2.toString());
					lpile1.add(p1.toString());
					act.add("Production E");
				}
				else{
					if(ss.equals("null"))
						accept=false;
					else{
						act.add("Production");
						st = new StringTokenizer(ss," ");
						n1=st.countTokens();
						for(i=0;i<n1;i++)
		                 {
			               p3.push(st.nextToken());
		                 }
						p2.pop();
		                   while(!p3.empty()){
			                    p2.push(p3.peek());
			                    p3.pop();
	                      	}
						   lpile.add(p2.toString());
						   lpile1.add(p1.toString());
					     }
				         }
			    }
		}
		}
		if(!( p1.empty() && p2.empty() )){
			accept=false;
		}
		if (accept){
			accpt.setVisible(true);
			
		}
		else{
			JOptionPane.showMessageDialog(null, "Problem writing : " + file.data , "Error", JOptionPane.ERROR_MESSAGE);
		}
  }
		
		
		

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
		dtype.setVisible(true);
		lval.removeAll();
		ltype.removeAll();
		int i=0;
		
		 for (i=0;i<nbtyp;i++){
			 lval.add(tbltyp[i].val);
			 ltype.add(tbltyp[i].ty);
		 }
		
		
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
		 try {
            //show file
            // TODO add your handling code here:
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + "C:\\Users\\Afak\\Desktop\\framecompl\\reader.txt");
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Check file details");
        }
		
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
		dtype.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
		//table follow first 
		dtbl.setVisible(true);
		lfirst.removeAll();
		lfollow.removeAll();
		lvn.removeAll();
		vt0.removeAll();
		vt1.removeAll();
		vt2.removeAll();
		vt3.removeAll();
		vt4.removeAll();
		vt5.removeAll();
		vt6.removeAll();
		vt7.removeAll();
		vt8.removeAll();
		t1.removeAll();
		t2.removeAll();
		t3.removeAll();
		t4.removeAll();
		t5.removeAll();
		t6.removeAll();
		t7.removeAll();
		t8.removeAll();
		t9.removeAll();
		int i=0,n=red.nb,j=0,k=red.tb;
        while(i<n)
        {
        lfirst.add(red.Vn[i] + "    ->    " + First[i]);
		lfollow.add(red.Vn[i] + "    ->     " + Follow[i]);
        i++;
        }
		
		// hada table analyse
		vt0.add(red.Vt[0].toString());
		vt1.add(red.Vt[1].toString());
		vt2.add(red.Vt[2].toString());
		vt3.add(red.Vt[3].toString());
		vt4.add(red.Vt[4].toString());
		vt5.add(red.Vt[5].toString());
		vt6.add(red.Vt[6].toString());
		vt7.add(red.Vt[7].toString());
		vt8.add(red.Vt[8].toString());
		for(i=0;i<n;i++){
			lvn.add(red.Vn[i].toString());
		}
		//t
		for(i=0;i<n;i++){
			t1.add(red.Table[i][0] .toString());
		}
		for(i=0;i<n;i++){
			t2.add(red.Table[i][1] .toString());
		}
		for(i=0;i<n;i++){
			t3.add(red.Table[i][2] .toString());
		}
		for(i=0;i<n;i++){
			t4.add(red.Table[i][3] .toString());
		}
		for(i=0;i<n;i++){
			t5.add(red.Table[i][4] .toString());
		}
		for(i=0;i<n;i++){
			t6.add(red.Table[i][5] .toString());
		}
		for(i=0;i<n;i++){
			t7.add(red.Table[i][6] .toString());
		}
		for(i=0;i<n;i++){
			t8.add(red.Table[i][7] .toString());
		}
		for(i=0;i<n;i++){
			t9.add(red.Table[i][8] .toString());
		}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
		dtbl.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
		accpt.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actActionPerformed

    private void lpileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lpileActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NewJFrame().setVisible(true);
			}
		});
	}

	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog accpt;
    private java.awt.List act;
    private javax.swing.JDialog dtbl;
    private javax.swing.JDialog dtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private java.awt.List lfirst;
    private java.awt.List lfollow;
    private java.awt.List lpile;
    private java.awt.List lpile1;
    private java.awt.List ltype;
    private java.awt.List lval;
    private java.awt.List lvn;
    private java.awt.List t1;
    private java.awt.List t2;
    private java.awt.List t3;
    private java.awt.List t4;
    private java.awt.List t5;
    private java.awt.List t6;
    private java.awt.List t7;
    private java.awt.List t8;
    private java.awt.List t9;
    private java.awt.List vt0;
    private java.awt.List vt1;
    private java.awt.List vt2;
    private java.awt.List vt3;
    private java.awt.List vt4;
    private java.awt.List vt5;
    private java.awt.List vt6;
    private java.awt.List vt7;
    private java.awt.List vt8;
    // End of variables declaration//GEN-END:variables
}
